#!/bin/bash

# This program is free software. It comes without any warranty, to the
# extent permitted by applicable law. You can redistribute it and/or modify
# it under the terms of the Do What The Fuck You Want To Public License,
# Version 2, as published by Sam Hocevar. See WTFPL.txt or
# http://www.wtfpl.net/ for more details.

include output
include fail
include error


function calculate() {
  # bc always returns zero, but outputs to stderr upon failure.  I want to fail
  # if it fails, and still show any output.
  #
  # Hold my beer and watch this.
  {
    bc <<< "scale=3; ${*}" 2>&1 1>&3 | { 
      read stderr
      grep -q . <<< "${stderr}" \
        && error "bc failed - stderr:" "'${stderr}'"
    } && fail "bc failed -   math:" "'${*}'"
  } 3>&1
  true
}
