#!/bin/bash

# This program is free software. It comes without any warranty, to the
# extent permitted by applicable law. You can redistribute it and/or modify
# it under the terms of the Do What The Fuck You Want To Public License,
# Version 2, as published by Sam Hocevar. See WTFPL.txt or
# http://www.wtfpl.net/ for more details.

include calculate
include fail


function calculate_points_per_serving() {
  # Parameters should be checked already.
  food="${1}"
  calories="${2}"
  fat="${3}"
  fiber="${4}"

  # min(fiber, 4)
  fiber="$(calculate "if (${fiber}>4) 4 else ${fiber}")" \
    || fail "Failed to calculate fiber."

  # The forumula, except for the min(fiber, 4) part, which is done above.
  points=$(
    calculate "(${calories} / 50) + (${fat} / 12) - (${fiber} / 5)"
  ) || fail "Failed to calculate points."

  printf '%s\n' ${points}
}
