#!/bin/bash

# This program is free software. It comes without any warranty, to the
# extent permitted by applicable law. You can redistribute it and/or modify
# it under the terms of the Do What The Fuck You Want To Public License,
# Version 2, as published by Sam Hocevar. See WTFPL.txt or
# http://www.wtfpl.net/ for more details.

script_name="${0##*/}"
PREFIX="${script_name}:  "
DATE="$(date "+%Y%m%d")"
if test 6 -gt "$(date '+%H')"; then
  DATE="$(( DATE - 1 ))"
fi
state="${main_dir}/state"
TAB="${state}/days/${DATE}"
weigh_in="${state}/weights/${DATE}"
foods="${state}/foods"
