#!/bin/bash

# This program is free software. It comes without any warranty, to the
# extent permitted by applicable law. You can redistribute it and/or modify
# it under the terms of the Do What The Fuck You Want To Public License,
# Version 2, as published by Sam Hocevar. See WTFPL.txt or
# http://www.wtfpl.net/ for more details.

include mkstate
include sync_state
include distill
include prompt
include new_food
include interactive
include output
include config
include fail
include warn


function food() {
  mkstate
  sync_state
  prompt "Food:"
  read food

  if test -f "${state}/foods/${food}"; then
    if serving_size="$(< "${state}/serving_sizes/${food}")"; then
      output "Serving size:" "${serving_size}"
    else
      warn "Failed to get serving size for:" "${food}"
    fi
    points_per_serving="$(distill "$(< "${state}/foods/${food}")")" \
      || fail "Failed to get points per serving."
    output "Points per serving:" "${points_per_serving}"
    prompt "Overwrite?  [y,N]"
    read response
    if grep -qi 'y' <<< "${response}"; then
      > "${state}/foods/${food}"
      new_food "${food}"
    fi
  else
    if interactive; then
      new_food "${food}"
    else
      fail "Unknown food:  ${food}"
    fi
  fi
  sync_state
}
