#!/bin/bash

# This program is free software. It comes without any warranty, to the
# extent permitted by applicable law. You can redistribute it and/or modify
# it under the terms of the Do What The Fuck You Want To Public License,
# Version 2, as published by Sam Hocevar. See WTFPL.txt or
# http://www.wtfpl.net/ for more details.


function distill() {
  sed 's/[^0-9\.]//g' \
    <<< "${*}" \
    | head -n 1
}


function output() {
  prompt "${1}"
  shift 1
  printf '%s\n' "${*}"
}


function prompt() {
  printf '%s  %48s' "${PREFIX}" "${1}  "
}


function error() {
  output "ERROR:  ${1}" >&2
}


function debug() {
  if test 'set' = "${debug:+set}"; then
    output "DEBUG:  ${1}" >&2
  fi
}


function fail() {
  error "${1}"
  exit "${2:-1}"
}


function interactive() {
  if test 'set' = "${NONINTERACTIVE:+set}"; then
    false
  else
    true
  fi
}
