#!/bin/bash

# This program is free software. It comes without any warranty, to the
# extent permitted by applicable law. You can redistribute it and/or modify
# it under the terms of the Do What The Fuck You Want To Public License,
# Version 2, as published by Sam Hocevar. See WTFPL.txt or
# http://www.wtfpl.net/ for more details.


function distill() {
  sed 's/[^0-9\.]//g' \
    <<< "${*}" \
    | head -n 1
}


function output() {
  prompt "${1}"
  shift 1
  printf '%s\n' "${*}"
}


function prompt() {
  offset="${#prefix}"
  prompt_length="$(( 60 - offset ))"
  printf "%s  %${prompt_length}s" "${prefix}" "${1}  "
}


function error() {
  prefix="${prefix}ERROR:  " output "${@}" >&2
}


function warn() {
  prefix="${prefix}WARNING:  " output "${@}" >&2
}


function debug() {
  if test 'set' = "${debug:+set}"; then
    prefix="${prefix}DEBUG:  " output "${@}" >&2
  fi
}


function fail() {
  error "${@}"
  exit 1
}


function interactive() {
  if test 'set' = "${NONINTERACTIVE:+set}"; then
    false
  else
    true
  fi
}
