#!/bin/bash

# This program is free software. It comes without any warranty, to the
# extent permitted by applicable law. You can redistribute it and/or modify
# it under the terms of the Do What The Fuck You Want To Public License,
# Version 2, as published by Sam Hocevar. See WTFPL.txt or
# http://www.wtfpl.net/ for more details.


function new_food
{
  FOOD="${1}"
  # Get details from the user.
  prompt "Calories per serving:"
  read CALORIES
  prompt "Grams of fat per serving:"
  read FAT
  prompt "Grams of dietary fiber per serving:"
  read FIBER

  # Check validity of input.
  for VAR in CALORIES FAT FIBER
  do
    eval $VAR=$(distill "${!VAR}")
    if [ "${!VAR}" == "" ]
    then
      fail "Invalid number for ${VAR}."
    fi
  done

  # The heavy lifting.
  POINTS=$(serving_points "${FOOD}" "${CALORIES}" "${FAT}" "${FIBER}")

  output
  output "Points:" "${POINTS}"

  # Save the points per serving for this food.
  printf "%s\n" "${POINTS}" > state/foods/"${FOOD}"
}
