#!/bin/bash

# This program is free software. It comes without any warranty, to the
# extent permitted by applicable law. You can redistribute it and/or modify
# it under the terms of the Do What The Fuck You Want To Public License,
# Version 2, as published by Sam Hocevar. See WTFPL.txt or
# http://www.wtfpl.net/ for more details.


function new_food
{
  food="${1}"
  # Get details from the user.
  prompt "Calories per serving:"
  read calories
  prompt "Grams of fat per serving:"
  read fat
  prompt "Grams of dietary fiber per serving:"
  read fiber

  # Check validity of input.
  for var in calories fat fiber
  do
    eval $var=$(distill "${!var}")
    if [ "${!var}" == "" ]
    then
      fail "Invalid number for ${var}."
    fi
  done

  # The heavy lifting.
  points=$(serving_points "${food}" "${calories}" "${fat}" "${fiber}")

  output "Points per serving:" "${points}"

  # Save the points per serving for this food.
  printf "%s\n" "${points}" > "${foods}/${food}"
}
