#!/bin/bash

# This program is free software. It comes without any warranty, to the
# extent permitted by applicable law. You can redistribute it and/or modify
# it under the terms of the Do What The Fuck You Want To Public License,
# Version 2, as published by Sam Hocevar. See WTFPL.txt or
# http://www.wtfpl.net/ for more details.


function serving_points
{
  # Parameters should be checked already.
  food="${1}"
  calories="${2}"
  fat="${3}"
  fiber="${4}"

  # min(fiber, 4)
  if [ "$(
    bc <<< "a=${fiber}; b=4; r=-1; if (a>b) r=1; r"
  )" == "1" ]
  then fiber=4
  fi
  debug "fiber:  ${fiber}"

  # The forumula, except for the min(fiber, 4) part, which is done above.
  points=$(
    bc <<< "scale=3; (${calories} / 50) + (${fat} / 12) - (${fiber} / 5)"
  )

  printf '%s\n' ${points}
}
