#!/bin/bash

# This program is free software. It comes without any warranty, to the
# extent permitted by applicable law. You can redistribute it and/or modify
# it under the terms of the Do What The Fuck You Want To Public License,
# Version 2, as published by Sam Hocevar. See WTFPL.txt or
# http://www.wtfpl.net/ for more details.

include real_tally
include config
include fail


# Tally up the log, then take new input from the user.
function tally_then_tally() {
    tally=0
    if [ -f "${log}" ]; then
      tally="$(NONINTERACTIVE='y' real_tally < "${log}")" \
        || fail "Failed to tally existing tab."
    fi
    real_tally
}
