#!/bin/bash

# This program is free software. It comes without any warranty, to the
# extent permitted by applicable law. You can redistribute it and/or modify
# it under the terms of the Do What The Fuck You Want To Public License,
# Version 2, as published by Sam Hocevar. See WTFPL.txt or
# http://www.wtfpl.net/ for more details.


function weigh_in() {
  unset weight
  if test -e "${weigh_in}"; then
    read weight_raw < "${weigh_in}"
    weight="$(distill "${weight_raw}")"
    if grep -q . <<< "${weight}"; then
      output "Weight:" "${weight}"
    else
      warn "Invalid weight:" "${weight_raw}"
      rm "${weigh_in}" \
        || fail "Failed to remove corrupt weight file:  ${weigh_in}"
      weigh_in
    fi
  else
    prompt "Weight (lbs):"
    read response
    weight="$(distill "${response}")"
    if grep -q . <<< "${weight}"; then
      printf '%s\n' "${weight}" > "${weigh_in}"
    else
      warn "Invalid weight:" "${response}"
      output "Skipping weigh in."
    fi
  fi
}
