#!/bin/bash

# This program is free software. It comes without any warranty, to the
# extent permitted by applicable law. You can redistribute it and/or modify
# it under the terms of the Do What The Fuck You Want To Public License,
# Version 2, as published by Sam Hocevar. See WTFPL.txt or
# http://www.wtfpl.net/ for more details.

include distill
include prompt
include weigh_in
include output
include config
include fail


# Provide the option to overwrite, then weigh in.
function weigh_in_assertively() {
  if test -f "${weigh_in}"; then
    weight="$(distill "$(< "${weigh_in}")")" \
      || fail "Failed to read weight."
    output "Weight:" "${weight}"
    prompt "Overwrite?  [y,N]"
    read response
    if ! grep -qi 'y' <<< "${response}"; then
      exit 0
    fi
    rm "${weigh_in}" \
      || fail "Failed to remove old weight file."
  fi
  weigh_in
}
