#!/bin/bash

# This program is free software. It comes without any warranty, to the
# extent permitted by applicable law. You can redistribute it and/or modify
# it under the terms of the Do What The Fuck You Want To Public License,
# Version 2, as published by Sam Hocevar. See WTFPL.txt or
# http://www.wtfpl.net/ for more details.


function weigh_in() {
  if test -e "${weigh_in}"; then
    read weight < "${weigh_in}"
    output "Today's weight:" "${weight}"
    prompt "[o]verwrite, [c]ontinue, or [a]bort?  [o,c,A]"
    read response
    if grep -qi 'c' <<< "${response}"; then
      return 0
    elif ! grep -qi 'o' <<< "${response}"; then
      return 1
    fi
  fi
  prompt "Weight (lbs):"
  read weight
  original_weight="${weight}"
  weight="$(distill "${weight}")"
  if ! grep -q . <<< "${weight}"; then
    fail "Invalid weight:  ${original_weight}"
  fi
  printf '%s\n' "${weight}" > "${weigh_in}"
}
